elemen_periodik = [
    {'simbol': 'H', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 1},
    {'simbol': 'He', 'golongan': 'gas mulia', 'baris': 1, 'kolom': 18},
    {'simbol': 'Li', 'golongan': 'logam alkali', 'baris': 2, 'kolom': 1},
    {'simbol': 'Be', 'golongan': 'logam alkali tanah', 'baris': 2, 'kolom': 2},
    {'simbol': 'B', 'golongan': 'metaloid', 'baris': 2, 'kolom': 13},
    {'simbol': 'C', 'golongan': 'nonlogam', 'baris': 2, 'kolom': 14},
    {'simbol': 'N', 'golongan': 'nonlogam', 'baris': 2, 'kolom': 15},
    {'simbol': 'O', 'golongan': 'nonlogam', 'baris': 2, 'kolom': 16},
    {'simbol': 'F', 'golongan': 'halogen', 'baris': 2, 'kolom': 17},
    {'simbol': 'Ne', 'golongan': 'gas mulia', 'baris': 2, 'kolom': 18},
    {'simbol': 'Na', 'golongan': 'logam alkali', 'baris': 3, 'kolom': 1},
    {'simbol': 'Mg', 'golongan': 'logam alkali tanah', 'baris': 3, 'kolom': 2},
    {'simbol': 'Al', 'golongan': 'logam pasca transisi', 'baris': 3, 'kolom': 13},
    {'simbol': 'Si', 'golongan': 'metaloid', 'baris': 3, 'kolom': 14},
    {'simbol': 'P', 'golongan': 'nonlogam', 'baris': 3, 'kolom': 15},
    {'simbol': 'S', 'golongan': 'nonlogam', 'baris': 3, 'kolom': 16},
    {'simbol': 'Cl', 'golongan': 'halogen', 'baris': 3, 'kolom': 17},
    {'simbol': 'Ar', 'golongan': 'gas mulia', 'baris': 3, 'kolom': 18},
    {'simbol': 'K', 'golongan': 'logam alkali', 'baris': 4, 'kolom': 1},
    {'simbol': 'Ca', 'golongan': 'logam alkali tanah', 'baris': 4, 'kolom': 2},
    {'simbol': 'Og', 'golongan': 'gas mulia', 'baris': 7, 'kolom': 18},
]

warna_golongan = {
    "logam alkali": "#FFA07A",
    "logam alkali tanah": "#F0E68C",
    "logam transisi": "#90EE90",
    "logam pasca transisi": "#D8BFD8",
    "metaloid": "#DDA0DD",
    "nonlogam": "#87CEFA",
    "halogen": "#FFD700",
    "gas mulia": "#AFEEEE",
    "lanthanida": "#FFB6C1",
    "aktinida": "#E6E6FA"
}
