elemen_periodik = [
    {'simbol': 'H', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 1},
    {'simbol': 'He', 'golongan': 'gas mulia', 'baris': 1, 'kolom': 2},
    {'simbol': 'Li', 'golongan': 'logam alkali', 'baris': 1, 'kolom': 3},
    {'simbol': 'Be', 'golongan': 'logam alkali tanah', 'baris': 1, 'kolom': 4},
    {'simbol': 'B', 'golongan': 'metaloid', 'baris': 1, 'kolom': 5},
    {'simbol': 'C', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 6},
    {'simbol': 'N', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 7},
    {'simbol': 'O', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 8},
    {'simbol': 'F', 'golongan': 'halogen', 'baris': 1, 'kolom': 9},
    {'simbol': 'Ne', 'golongan': 'gas mulia', 'baris': 1, 'kolom': 10},
    {'simbol': 'Na', 'golongan': 'logam alkali', 'baris': 1, 'kolom': 11},
    {'simbol': 'Mg', 'golongan': 'logam alkali tanah', 'baris': 1, 'kolom': 12},
    {'simbol': 'Al', 'golongan': 'logam pasca transisi', 'baris': 1, 'kolom': 13},
    {'simbol': 'Si', 'golongan': 'metaloid', 'baris': 1, 'kolom': 14},
    {'simbol': 'P', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 15},
    {'simbol': 'S', 'golongan': 'nonlogam', 'baris': 1, 'kolom': 16},
    {'simbol': 'Cl', 'golongan': 'halogen', 'baris': 1, 'kolom': 17},
    {'simbol': 'Ar', 'golongan': 'gas mulia', 'baris': 1, 'kolom': 18},
    {'simbol': 'K', 'golongan': 'logam alkali', 'baris': 2, 'kolom': 1},
    {'simbol': 'Ca', 'golongan': 'logam alkali tanah', 'baris': 2, 'kolom': 2},
    {'simbol': 'Sc', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 3},
    {'simbol': 'Ti', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 4},
    {'simbol': 'V', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 5},
    {'simbol': 'Cr', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 6},
    {'simbol': 'Mn', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 7},
    {'simbol': 'Fe', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 8},
    {'simbol': 'Co', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 9},
    {'simbol': 'Ni', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 10},
    {'simbol': 'Cu', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 11},
    {'simbol': 'Zn', 'golongan': 'logam transisi', 'baris': 2, 'kolom': 12},
    {'simbol': 'Ga', 'golongan': 'logam pasca transisi', 'baris': 2, 'kolom': 13},
    {'simbol': 'Ge', 'golongan': 'metaloid', 'baris': 2, 'kolom': 14},
    {'simbol': 'As', 'golongan': 'metaloid', 'baris': 2, 'kolom': 15},
    {'simbol': 'Se', 'golongan': 'nonlogam', 'baris': 2, 'kolom': 16},
    {'simbol': 'Br', 'golongan': 'halogen', 'baris': 2, 'kolom': 17},
    {'simbol': 'Kr', 'golongan': 'gas mulia', 'baris': 2, 'kolom': 18},
    {'simbol': 'Rb', 'golongan': 'logam alkali', 'baris': 3, 'kolom': 1},
    {'simbol': 'Sr', 'golongan': 'logam alkali tanah', 'baris': 3, 'kolom': 2},
    {'simbol': 'Y', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 3},
    {'simbol': 'Zr', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 4},
    {'simbol': 'Nb', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 5},
    {'simbol': 'Mo', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 6},
    {'simbol': 'Tc', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 7},
    {'simbol': 'Ru', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 8},
    {'simbol': 'Rh', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 9},
    {'simbol': 'Pd', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 10},
    {'simbol': 'Ag', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 11},
    {'simbol': 'Cd', 'golongan': 'logam transisi', 'baris': 3, 'kolom': 12},
    {'simbol': 'In', 'golongan': 'logam pasca transisi', 'baris': 3, 'kolom': 13},
    {'simbol': 'Sn', 'golongan': 'logam pasca transisi', 'baris': 3, 'kolom': 14},
    {'simbol': 'Sb', 'golongan': 'metaloid', 'baris': 3, 'kolom': 15},
    {'simbol': 'Te', 'golongan': 'metaloid', 'baris': 3, 'kolom': 16},
    {'simbol': 'I', 'golongan': 'halogen', 'baris': 3, 'kolom': 17},
    {'simbol': 'Xe', 'golongan': 'gas mulia', 'baris': 3, 'kolom': 18},
    {'simbol': 'Cs', 'golongan': 'logam alkali', 'baris': 4, 'kolom': 1},
    {'simbol': 'Ba', 'golongan': 'logam alkali tanah', 'baris': 4, 'kolom': 2},
    {'simbol': 'La', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 3},
    {'simbol': 'Ce', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 4},
    {'simbol': 'Pr', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 5},
    {'simbol': 'Nd', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 6},
    {'simbol': 'Pm', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 7},
    {'simbol': 'Sm', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 8},
    {'simbol': 'Eu', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 9},
    {'simbol': 'Gd', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 10},
    {'simbol': 'Tb', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 11},
    {'simbol': 'Dy', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 12},
    {'simbol': 'Ho', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 13},
    {'simbol': 'Er', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 14},
    {'simbol': 'Tm', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 15},
    {'simbol': 'Yb', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 16},
    {'simbol': 'Lu', 'golongan': 'lanthanida', 'baris': 4, 'kolom': 17},
    {'simbol': 'Hf', 'golongan': 'logam transisi', 'baris': 4, 'kolom': 18},
    {'simbol': 'Ta', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 1},
    {'simbol': 'W', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 2},
    {'simbol': 'Re', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 3},
    {'simbol': 'Os', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 4},
    {'simbol': 'Ir', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 5},
    {'simbol': 'Pt', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 6},
    {'simbol': 'Au', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 7},
    {'simbol': 'Hg', 'golongan': 'logam transisi', 'baris': 5, 'kolom': 8},
    {'simbol': 'Tl', 'golongan': 'logam pasca transisi', 'baris': 5, 'kolom': 9},
    {'simbol': 'Pb', 'golongan': 'logam pasca transisi', 'baris': 5, 'kolom': 10},
    {'simbol': 'Bi', 'golongan': 'logam pasca transisi', 'baris': 5, 'kolom': 11},
    {'simbol': 'Po', 'golongan': 'metaloid', 'baris': 5, 'kolom': 12},
    {'simbol': 'At', 'golongan': 'halogen', 'baris': 5, 'kolom': 13},
    {'simbol': 'Rn', 'golongan': 'gas mulia', 'baris': 5, 'kolom': 14},
    {'simbol': 'Fr', 'golongan': 'logam alkali', 'baris': 5, 'kolom': 15},
    {'simbol': 'Ra', 'golongan': 'logam alkali tanah', 'baris': 5, 'kolom': 16},
    {'simbol': 'Ac', 'golongan': 'aktinida', 'baris': 5, 'kolom': 17},
    {'simbol': 'Th', 'golongan': 'aktinida', 'baris': 5, 'kolom': 18},
    {'simbol': 'Pa', 'golongan': 'aktinida', 'baris': 6, 'kolom': 1},
    {'simbol': 'U', 'golongan': 'aktinida', 'baris': 6, 'kolom': 2},
    {'simbol': 'Np', 'golongan': 'aktinida', 'baris': 6, 'kolom': 3},
    {'simbol': 'Pu', 'golongan': 'aktinida', 'baris': 6, 'kolom': 4},
    {'simbol': 'Am', 'golongan': 'aktinida', 'baris': 6, 'kolom': 5},
    {'simbol': 'Cm', 'golongan': 'aktinida', 'baris': 6, 'kolom': 6},
    {'simbol': 'Bk', 'golongan': 'aktinida', 'baris': 6, 'kolom': 7},
    {'simbol': 'Cf', 'golongan': 'aktinida', 'baris': 6, 'kolom': 8},
    {'simbol': 'Es', 'golongan': 'aktinida', 'baris': 6, 'kolom': 9},
    {'simbol': 'Fm', 'golongan': 'aktinida', 'baris': 6, 'kolom': 10},
    {'simbol': 'Md', 'golongan': 'aktinida', 'baris': 6, 'kolom': 11},
    {'simbol': 'No', 'golongan': 'aktinida', 'baris': 6, 'kolom': 12},
    {'simbol': 'Lr', 'golongan': 'aktinida', 'baris': 6, 'kolom': 13},
    {'simbol': 'Rf', 'golongan': 'logam transisi', 'baris': 6, 'kolom': 14},
    {'simbol': 'Db', 'golongan': 'logam transisi', 'baris': 6, 'kolom': 15},
    {'simbol': 'Sg', 'golongan': 'logam transisi', 'baris': 6, 'kolom': 16},
    {'simbol': 'Bh', 'golongan': 'logam transisi', 'baris': 6, 'kolom': 17},
    {'simbol': 'Hs', 'golongan': 'logam transisi', 'baris': 6, 'kolom': 18},
    {'simbol': 'Mt', 'golongan': 'logam transisi', 'baris': 7, 'kolom': 1},
    {'simbol': 'Ds', 'golongan': 'logam transisi', 'baris': 7, 'kolom': 2},
    {'simbol': 'Rg', 'golongan': 'logam transisi', 'baris': 7, 'kolom': 3},
    {'simbol': 'Cn', 'golongan': 'logam transisi', 'baris': 7, 'kolom': 4},
    {'simbol': 'Nh', 'golongan': 'logam pasca transisi', 'baris': 7, 'kolom': 5},
    {'simbol': 'Fl', 'golongan': 'logam pasca transisi', 'baris': 7, 'kolom': 6},
    {'simbol': 'Mc', 'golongan': 'logam pasca transisi', 'baris': 7, 'kolom': 7},
    {'simbol': 'Lv', 'golongan': 'logam pasca transisi', 'baris': 7, 'kolom': 8},
    {'simbol': 'Ts', 'golongan': 'halogen', 'baris': 7, 'kolom': 9},
    {'simbol': 'Og', 'golongan': 'gas mulia', 'baris': 7, 'kolom': 10},
]

warna_golongan = {
    "logam alkali": "#FFA07A",
    "logam alkali tanah": "#F0E68C",
    "logam transisi": "#90EE90",
    "logam pasca transisi": "#D8BFD8",
    "metaloid": "#DDA0DD",
    "nonlogam": "#87CEFA",
    "halogen": "#FFD700",
    "gas mulia": "#AFEEEE",
    "lanthanida": "#FFB6C1",
    "aktinida": "#E6E6FA",
}
