massa_atom = {
     "H": 1.01, "He": 4.00, "Li": 6.94, "Be": 9.01, "B": 10.81, "C": 12.01, "N": 14.01, "O": 16.00, "F": 19.00, "Ne": 20.18,
    "Na": 22.99, "Mg": 24.31, "Al": 26.98, "Si": 28.09, "P": 30.97, "S": 32.07, "Cl": 35.45, "Ar": 39.95,
    "K": 39.10, "Ca": 40.08, "Sc": 44.96, "Ti": 47.87, "V": 50.94, "Cr": 52.00, "Mn": 54.94, "Fe": 55.85,
    "Co": 58.93, "Ni": 58.69, "Cu": 63.55, "Zn": 65.38, "Ga": 69.72, "Ge": 72.63, "As": 74.92, "Se": 78.97,
    "Br": 79.90, "Kr": 83.80, "Rb": 85.47, "Sr": 87.62, "Y": 88.91, "Zr": 91.22, "Nb": 92.91, "Mo": 95.95,
    "Tc": 98.00, "Ru": 101.1, "Rh": 102.9, "Pd": 106.4, "Ag": 107.9, "Cd": 112.4, "In": 114.8, "Sn": 118.7,
    "Sb": 121.8, "Te": 127.6, "I": 126.9, "Xe": 131.3, "Cs": 132.9, "Ba": 137.3, "La": 138.9, "Ce": 140.1,
    "Pr": 140.9, "Nd": 144.2, "Pm": 145.0, "Sm": 150.4, "Eu": 152.0, "Gd": 157.3, "Tb": 158.9, "Dy": 162.5,
    "Ho": 164.9, "Er": 167.3, "Tm": 168.9, "Yb": 173.0, "Lu": 175.0, "Hf": 178.5, "Ta": 180.9, "W": 183.8,
    "Re": 186.2, "Os": 190.2, "Ir": 192.2, "Pt": 195.1, "Au": 197.0, "Hg": 200.6, "Tl": 204.4, "Pb": 207.2,
    "Bi": 208.9, "Po": 209.0, "At": 210.0, "Rn": 222.0, "Fr": 223.0, "Ra": 226.0, "Ac": 227.0, "Th": 232.0,
    "Pa": 231.0, "U": 238.0, "Np": 237.0, "Pu": 244.0, "Am": 243.0, "Cm": 247.0, "Bk": 247.0, "Cf": 251.0,
    "Es": 252.0, "Fm": 257.0, "Md": 258.0, "No": 259.0, "Lr": 262.0, "Rf": 267.0, "Db": 270.0, "Sg": 271.0,
    "Bh": 270.0, "Hs": 277.0, "Mt": 276.0, "Ds": 281.0, "Rg": 280.0, "Cn": 285.0, "Nh": 284.0, "Fl": 289.0,
    "Mc": 288.0, "Lv": 293.0, "Ts": 294.0, "Og": 294.0
}

elemen_periodik = [
    # Baris 1
    [{"simbol": "H", "golongan": "nonlogam"}] + [{}]*16 + [{"simbol": "He", "golongan": "gas mulia"}],
    
    # Baris 2
    [{"simbol": "Li", "golongan": "logam alkali"},
     {"simbol": "Be", "golongan": "logam alkali tanah"}] + [{}]*10 + 
    [{"simbol": "B", "golongan": "metaloid"},
     {"simbol": "C", "golongan": "nonlogam"},
     {"simbol": "N", "golongan": "nonlogam"},
     {"simbol": "O", "golongan": "nonlogam"},
     {"simbol": "F", "golongan": "halogen"},
     {"simbol": "Ne", "golongan": "gas mulia"}],
    
    # Baris 3
    [{"simbol": "Na", "golongan": "logam alkali"},
     {"simbol": "Mg", "golongan": "logam alkali tanah"}] + [{}]*10 +
    [{"simbol": "Al", "golongan": "logam pasca transisi"},
     {"simbol": "Si", "golongan": "metaloid"},
     {"simbol": "P", "golongan": "nonlogam"},
     {"simbol": "S", "golongan": "nonlogam"},
     {"simbol": "Cl", "golongan": "halogen"},
     {"simbol": "Ar", "golongan": "gas mulia"}],

    # Baris 4
    [{"simbol": "K", "golongan": "logam alkali"},
     {"simbol": "Ca", "golongan": "logam alkali tanah"},
     {"simbol": "Sc", "golongan": "logam transisi"},
     {"simbol": "Ti", "golongan": "logam transisi"},
     {"simbol": "V", "golongan": "logam transisi"},
     {"simbol": "Cr", "golongan": "logam transisi"},
     {"simbol": "Mn", "golongan": "logam transisi"},
     {"simbol": "Fe", "golongan": "logam transisi"},
     {"simbol": "Co", "golongan": "logam transisi"},
     {"simbol": "Ni", "golongan": "logam transisi"},
     {"simbol": "Cu", "golongan": "logam transisi"},
     {"simbol": "Zn", "golongan": "logam transisi"},
     {"simbol": "Ga", "golongan": "logam pasca transisi"},
     {"simbol": "Ge", "golongan": "metaloid"},
     {"simbol": "As", "golongan": "metaloid"},
     {"simbol": "Se", "golongan": "nonlogam"},
     {"simbol": "Br", "golongan": "halogen"},
     {"simbol": "Kr", "golongan": "gas mulia"}],

    # Baris 5
    [{"simbol": "Rb", "golongan": "logam alkali"},
     {"simbol": "Sr", "golongan": "logam alkali tanah"},
     {"simbol": "Y", "golongan": "logam transisi"},
     {"simbol": "Zr", "golongan": "logam transisi"},
     {"simbol": "Nb", "golongan": "logam transisi"},
     {"simbol": "Mo", "golongan": "logam transisi"},
     {"simbol": "Tc", "golongan": "logam transisi"},
     {"simbol": "Ru", "golongan": "logam transisi"},
     {"simbol": "Rh", "golongan": "logam transisi"},
     {"simbol": "Pd", "golongan": "logam transisi"},
     {"simbol": "Ag", "golongan": "logam transisi"},
     {"simbol": "Cd", "golongan": "logam transisi"},
     {"simbol": "In", "golongan": "logam pasca transisi"},
     {"simbol": "Sn", "golongan": "logam pasca transisi"},
     {"simbol": "Sb", "golongan": "metaloid"},
     {"simbol": "Te", "golongan": "metaloid"},
     {"simbol": "I", "golongan": "halogen"},
     {"simbol": "Xe", "golongan": "gas mulia"}],

    # Baris 6
    [{"simbol": "Cs", "golongan": "logam alkali"},
     {"simbol": "Ba", "golongan": "logam alkali tanah"}] +
     [{"simbol": ""}] * 2 +
     [{"simbol": "La", "golongan": "lanthanida"},
      {"simbol": "Ce", "golongan": "lanthanida"},
      {"simbol": "Pr", "golongan": "lanthanida"},
      {"simbol": "Nd", "golongan": "lanthanida"},
      {"simbol": "Pm", "golongan": "lanthanida"},
      {"simbol": "Sm", "golongan": "lanthanida"},
      {"simbol": "Eu", "golongan": "lanthanida"},
      {"simbol": "Gd", "golongan": "lanthanida"},
      {"simbol": "Tb", "golongan": "lanthanida"},
      {"simbol": "Dy", "golongan": "lanthanida"},
      {"simbol": "Ho", "golongan": "lanthanida"},
      {"simbol": "Er", "golongan": "lanthanida"},
      {"simbol": "Tm", "golongan": "lanthanida"},
      {"simbol": "Yb", "golongan": "lanthanida"},
      {"simbol": "Lu", "golongan": "lanthanida"}] +
     [{"simbol": "Hf", "golongan": "logam transisi"},
      {"simbol": "Ta", "golongan": "logam transisi"},
      {"simbol": "W", "golongan": "logam transisi"},
      {"simbol": "Re", "golongan": "logam transisi"},
      {"simbol": "Os", "golongan": "logam transisi"},
      {"simbol": "Ir", "golongan": "logam transisi"},
      {"simbol": "Pt", "golongan": "logam transisi"},
      {"simbol": "Au", "golongan": "logam transisi"},
      {"simbol": "Hg", "golongan": "logam transisi"},
      {"simbol": "Tl", "golongan": "logam pasca transisi"},
      {"simbol": "Pb", "golongan": "logam pasca transisi"},
      {"simbol": "Bi", "golongan": "logam pasca transisi"},
      {"simbol": "Po", "golongan": "metaloid"},
      {"simbol": "At", "golongan": "halogen"},
      {"simbol": "Rn", "golongan": "gas mulia"}],

    # Baris 7
    [{"simbol": "Fr", "golongan": "logam alkali"},
     {"simbol": "Ra", "golongan": "logam alkali tanah"}] +
     [{"simbol": ""}] * 2 +
     [{"simbol": "Ac", "golongan": "aktinida"},
      {"simbol": "Th", "golongan": "aktinida"},
      {"simbol": "Pa", "golongan": "aktinida"},
      {"simbol": "U", "golongan": "aktinida"},
      {"simbol": "Np", "golongan": "aktinida"},
      {"simbol": "Pu", "golongan": "aktinida"},
      {"simbol": "Am", "golongan": "aktinida"},
      {"simbol": "Cm", "golongan": "aktinida"},
      {"simbol": "Bk", "golongan": "aktinida"},
      {"simbol": "Cf", "golongan": "aktinida"},
      {"simbol": "Es", "golongan": "aktinida"},
      {"simbol": "Fm", "golongan": "aktinida"},
      {"simbol": "Md", "golongan": "aktinida"},
      {"simbol": "No", "golongan": "aktinida"},
      {"simbol": "Lr", "golongan": "aktinida"}] +
     [{"simbol": "Rf", "golongan": "logam transisi"},
      {"simbol": "Db", "golongan": "logam transisi"},
      {"simbol": "Sg", "golongan": "logam transisi"},
      {"simbol": "Bh", "golongan": "logam transisi"},
      {"simbol": "Hs", "golongan": "logam transisi"},
      {"simbol": "Mt", "golongan": "logam transisi"},
      {"simbol": "Ds", "golongan": "logam transisi"},
      {"simbol": "Rg", "golongan": "logam transisi"},
      {"simbol": "Cn", "golongan": "logam transisi"},
      {"simbol": "Nh", "golongan": "logam pasca transisi"},
      {"simbol": "Fl", "golongan": "logam pasca transisi"},
      {"simbol": "Mc", "golongan": "logam pasca transisi"},
      {"simbol": "Lv", "golongan": "logam pasca transisi"},
      {"simbol": "Ts", "golongan": "halogen"},
      {"simbol": "Og", "golongan": "gas mulia"}]
]

Ar_tiap_unsur = massa_atom

element_info = {
    "Na": {"nama": "Natrium", "golongan": "logam alkali", "status": "logam", "kegunaan": "lampu uap natrium, garam dapur"},
    "Mg": {"nama": "Magnesium", "golongan": "logam alkali tanah", "status": "logam", "kegunaan": "kembang api, paduan logam ringan"},
    "Al": {"nama": "Aluminium", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "pembungkus makanan (aluminium foil), pesawat terbang"},
    "Si": {"nama": "Silikon", "golongan": "metaloid", "status": "metaloid", "kegunaan": "komponen utama semikonduktor"},
    "P":  {"nama": "Fosfor", "golongan": "nonlogam", "status": "nonlogam", "kegunaan": "pupuk, bahan peledak"},
    "S":  {"nama": "Sulfur", "golongan": "nonlogam", "status": "nonlogam", "kegunaan": "bahan baku asam sulfat, fungisida"},
    "Cl": {"nama": "Klorin", "golongan": "halogen", "status": "nonlogam", "kegunaan": "disinfektan, pemutih"},
    "Ar": {"nama": "Argon", "golongan": "gas mulia", "status": "nonlogam", "kegunaan": "lampu pijar, atmosfer inert"},
    "K":  {"nama": "Kalium", "golongan": "logam alkali", "status": "logam", "kegunaan": "pupuk, elektrolit biologis"},
    "Ca": {"nama": "Kalsium", "golongan": "logam alkali tanah", "status": "logam", "kegunaan": "tulang dan gigi, bahan bangunan (kapur)"},
    "Sc": {"nama": "Skandium", "golongan": "logam transisi", "status": "logam", "kegunaan": "lampu logam halida, paduan aluminium"},
    "Ti": {"nama": "Titanium", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan ringan tahan korosi, implan medis"},
    "V":  {"nama": "Vanadium", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan baja tahan karat"},
    "Cr": {"nama": "Kromium", "golongan": "logam transisi", "status": "logam", "kegunaan": "pelapis anti karat, stainless steel"},
    "Mn": {"nama": "Mangan", "golongan": "logam transisi", "status": "logam", "kegunaan": "pembuatan baja, baterai kering"},
    "Fe": {"nama": "Besi", "golongan": "logam transisi", "status": "logam", "kegunaan": "struktur bangunan, baja"},
    "Co": {"nama": "Kobalt", "golongan": "logam transisi", "status": "logam", "kegunaan": "baterai lithium-ion, magnet"},
    "Ni": {"nama": "Nikel", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan logam, koin"},
    "Cu": {"nama": "Tembaga", "golongan": "logam transisi", "status": "logam", "kegunaan": "kabel listrik, pipa air"},
    "Zn": {"nama": "Seng", "golongan": "logam transisi", "status": "logam", "kegunaan": "pelapis galvanis, paduan kuningan"},
    "Ga": {"nama": "Galium", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "termometer suhu tinggi, semikonduktor"},
    "Ge": {"nama": "Germanium", "golongan": "metaloid", "status": "padat", "kegunaan": "serat optik, transistor"},
    "As": {"nama": "Arsen", "golongan": "metaloid", "status": "padat", "kegunaan": "insektisida, semikonduktor"},
    "Se": {"nama": "Selenium", "golongan": "nonlogam", "status": "padat", "kegunaan": "fotovoltaik, kaca"},
    "Br": {"nama": "Brom", "golongan": "halogen", "status": "cair", "kegunaan": "pestisida, zat pewarna"},
    "Kr": {"nama": "Kripton", "golongan": "gas mulia", "status": "gas", "kegunaan": "lampu kilat fotografi, pencahayaan"},
    "Rb": {"nama": "Rubidium", "golongan": "logam alkali", "status": "logam", "kegunaan": "penelitian dan aplikasi fotolistrik"},
    "Sr": {"nama": "Stronsium", "golongan": "logam alkali tanah", "status": "logam", "kegunaan": "kembang api merah, implan gigi"},
    "Y":  {"nama": "Yttrium", "golongan": "logam transisi", "status": "logam", "kegunaan": "fosfor CRT, superkonduktor"},
    "Zr": {"nama": "Zirkonium", "golongan": "logam transisi", "status": "logam", "kegunaan": "reaktor nuklir, perhiasan imitasi"},
    "Nb": {"nama": "Niobium", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan baja, superkonduktor"},
    "Mo": {"nama": "Molibdenum", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan tahan panas, pelumas industri"},
    "Tc": {"nama": "Teknesium", "golongan": "logam transisi", "status": "radioaktif", "kegunaan": "medis nuklir (pemindaian)"},
    "Ru": {"nama": "Rutenium", "golongan": "logam transisi", "status": "logam", "kegunaan": "katalis, paduan tahan korosi"},
    "Rh": {"nama": "Rodium", "golongan": "logam transisi", "status": "logam", "kegunaan": "pelapis reflektif, katalis mobil"},
    "Pd": {"nama": "Palladium", "golongan": "logam transisi", "status": "logam", "kegunaan": "penyaring gas, paduan perhiasan"},
    "Ag": {"nama": "Perak", "golongan": "logam transisi", "status": "logam", "kegunaan": "perhiasan, konduktor listrik terbaik"},
    "Cd": {"nama": "Kadmium", "golongan": "logam transisi", "status": "logam", "kegunaan": "baterai NiCd, pelapis logam"},
    "In": {"nama": "Indium", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "layar sentuh, paduan logam rendah titik leleh"},
    "Sn": {"nama": "Timah", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "solder, kaleng makanan"},
    "Sb": {"nama": "Antimon", "golongan": "metaloid", "status": "padat", "kegunaan": "paduan timah, semikonduktor"},
    "Te": {"nama": "Telurium", "golongan": "metaloid", "status": "padat", "kegunaan": "paduan logam, industri kaca"},
    "I":  {"nama": "Iodin", "golongan": "halogen", "status": "padat", "kegunaan": "antiseptik, garam beryodium"},
    "Xe": {"nama": "Xenon", "golongan": "gas mulia", "status": "gas", "kegunaan": "lampu kilat, anestesi"},
    "Cs": {"nama": "Sesium", "golongan": "logam alkali", "status": "logam", "kegunaan": "jam atom, sel fotoelektrik"},
    "Ba": {"nama": "Barium", "golongan": "logam alkali tanah", "status": "logam", "kegunaan": "radiologi medis, kembang api hijau"},
    "La": {"nama": "Lantanum", "golongan": "lantanida", "status": "logam", "kegunaan": "elektroda karbon, optik"},
    "Ce": {"nama": "Serium", "golongan": "lantanida", "status": "logam", "kegunaan": "polesan kaca, katalis"},
    "Pr": {"nama": "Praseodimium", "golongan": "lantanida", "status": "logam", "kegunaan": "magnet permanen, lampu busur karbon"},
    "Nd": {"nama": "Neodimium", "golongan": "lantanida", "status": "logam", "kegunaan": "magnet kuat, laser"},
    "Pm": {"nama": "Prometium", "golongan": "lantanida", "status": "radioaktif", "kegunaan": "baterai nuklir, penelitian"},
    "Sm": {"nama": "Samarium", "golongan": "lantanida", "status": "logam", "kegunaan": "magnet, reaktor nuklir"},
    "Eu": {"nama": "Europium", "golongan": "lantanida", "status": "logam", "kegunaan": "lampu fluoresen, TV warna"},
    "Gd": {"nama": "Gadolinium", "golongan": "lantanida", "status": "logam", "kegunaan": "MRI, kontrol reaktor nuklir"},
    "Tb": {"nama": "Terbium", "golongan": "lantanida", "status": "logam", "kegunaan": "lampu neon, bahan magnetik"},
    "Dy": {"nama": "Disprosium", "golongan": "lantanida", "status": "logam", "kegunaan": "magnet, laser, reaktor nuklir"},
    "Ho": {"nama": "Holmium", "golongan": "lantanida", "status": "logam", "kegunaan": "magnet kuat, alat medis"},
    "Er": {"nama": "Erbium", "golongan": "lantanida", "status": "logam", "kegunaan": "penguat sinyal serat optik, laser medis"},
    "Tm": {"nama": "Tulium", "golongan": "lantanida", "status": "logam", "kegunaan": "laser portabel, X-ray"},
    "Yb": {"nama": "Iterbium", "golongan": "lantanida", "status": "logam", "kegunaan": "pendeteksi tekanan, semikonduktor"},
    "Lu": {"nama": "Lutesium", "golongan": "lantanida", "status": "logam", "kegunaan": "katalis, radioterapi kanker"},
    "Hf": {"nama": "Hafnium", "golongan": "logam transisi", "status": "logam", "kegunaan": "paduan reaktor nuklir, chip komputer"},
    "Ta": {"nama": "Tantalum", "golongan": "logam transisi", "status": "logam", "kegunaan": "kapasitor elektronik, alat bedah"},
    "W":  {"nama": "Tungsten", "golongan": "logam transisi", "status": "logam", "kegunaan": "filamen lampu, alat pemotong logam"},
    "Re": {"nama": "Renium", "golongan": "logam transisi", "status": "logam", "kegunaan": "turbin jet, kontak listrik"},
    "Os": {"nama": "Osmium", "golongan": "logam transisi", "status": "logam", "kegunaan": "pena mewah, kontak listrik"},
    "Ir": {"nama": "Iridium", "golongan": "logam transisi", "status": "logam", "kegunaan": "komponen mesin, pemancar radioaktif"},
    "Pt": {"nama": "Platina", "golongan": "logam transisi", "status": "logam", "kegunaan": "perhiasan, katalis knalpot mobil"},
    "Au": {"nama": "Emas", "golongan": "logam transisi", "status": "logam", "kegunaan": "perhiasan, sirkuit elektronik"},
    "Hg": {"nama": "Raksa", "golongan": "logam transisi", "status": "cair", "kegunaan": "termometer, lampu UV"},
    "Tl": {"nama": "Talium", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "detektor inframerah, pestisida (terbatas)"},
    "Pb": {"nama": "Timbal", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "baterai asam timbal, pelindung radiasi"},
    "Bi": {"nama": "Bismut", "golongan": "logam pasca transisi", "status": "logam", "kegunaan": "obat lambung, kosmetik"},
    "Po": {"nama": "Polonium", "golongan": "metaloid", "status": "radioaktif", "kegunaan": "sumber panas radioaktif, antistatik"},
    "At": {"nama": "Astatin", "golongan": "halogen", "status": "radioaktif", "kegunaan": "penelitian medis, terapi kanker (eksperimental)"},
    "Rn": {"nama": "Radon", "golongan": "gas mulia", "status": "gas radioaktif", "kegunaan": "radioterapi, pemantauan kualitas udara"},
    "Fr": {"nama": "Fransium", "golongan": "logam alkali", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "Ra": {"nama": "Radium", "golongan": "logam alkali tanah", "status": "radioaktif", "kegunaan": "radioterapi (sejarah), penelitian"},
    "Ac": {"nama": "Aktinium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "sumber neutron, terapi kanker"},
    "Th": {"nama": "Torium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "bahan bakar nuklir, keramik"},
    "Pa": {"nama": "Protaktinium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "U":  {"nama": "Uranium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "bahan bakar reaktor nuklir, senjata nuklir"},
    "Np": {"nama": "Neptunium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "bahan bakar reaktor cepat, penelitian"},
    "Pu": {"nama": "Plutonium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "senjata nuklir, pembangkit listrik nuklir"},
    "Am": {"nama": "Amerisium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "detektor asap, penelitian"},
    "Cm": {"nama": "Kuriun", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah, sumber tenaga"},
    "Bk": {"nama": "Berkelium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "sintesis unsur superberat"},
    "Cf": {"nama": "Kalifornium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "sumber neutron, pemindai logam"},
    "Es": {"nama": "Einsteinium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "Fm": {"nama": "Fermium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "Md": {"nama": "Mendelevium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "No": {"nama": "Nobelium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "Lr": {"nama": "Lawrensium", "golongan": "aktinida", "status": "radioaktif", "kegunaan": "penelitian ilmiah"},
    "Rf": {"nama": "Rutherfordium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Db": {"nama": "Dubnium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Sg": {"nama": "Seaborgium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Bh": {"nama": "Bohrium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Hs": {"nama": "Hassium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Mt": {"nama": "Meitnerium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Ds": {"nama": "Darmstadtium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Rg": {"nama": "Roentgenium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Cn": {"nama": "Copernicium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Nh": {"nama": "Nihonium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Fl": {"nama": "Flerovium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Mc": {"nama": "Moscovium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Lv": {"nama": "Livermorium", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Ts": {"nama": "Tennessine", "golongan": "unsur transaktinida", "status": "sintetik", "kegunaan": "penelitian"},
    "Og": {"nama": "Oganesson", "golongan": "gas mulia", "status": "sintetik", "kegunaan": "penelitian"}
}

